export default {
  IS_CART_OPENED: "IS_CART_OPENED",
  IS_MODAL_OPENED: "IS_MODAL_OPENED",
  IS_HEADER_MENU_OPENED: "IS_HEADER_MENU_OPENED",
  SET_FILTERS: "SET_FILTERS",
  SET_SORT_TYPE: "SET_SORT_TYPE",
  ADD_TO_CART: "ADD_TO_CART",
  RESET_CART: "RESET_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_COUNTER: "INCREASE_COUNTER",
  DECREASE_COUNTER: "DECREASE_COUNTER",
};
